name: Go Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'  # Updated Go version

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Tidy go.mod and go.sum
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Run Unit Tests (tests/unit)
        run: go test -v ./tests/unit/

      - name: Run Unit Tests with Coverage
        run: |
          go test -coverprofile=coverage.out ./tests/unit/
          go tool cover -func=coverage.out

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage
          path: coverage.out
